### ISSUE TITLE
Cannot unmarshal JSON array `[...]` into `map[string]any`

### ISSUE THREAD

**Issue by Vovan-VE** [green-api/whatsapp-api-client-golang#13]
Some API methods like [GetContacts](https://greenapi.com/en/docs/api/service/GetContacts/) return JSON array `[...]`. However all API methods on Go side unserializing into `map[string]any`, so it always errored for such API methods.
```
Unmarshal: json: cannot unmarshal array into Go value of type map[string]interface {}
```
https://github.com/green-api/whatsapp-api-client-golang/blob/e29e7146e757cad1d6843e968bb52ae4b7e398ff/pkg/api/http.go#L144-L151

**Comment by EscHelpNew** [comment]
The error has been fixed, thanks for contacting us!
